version: '3.8'

services:
  flaredock:
    build: .
    container_name: flaredock
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
      - CF_ACCOUNT_ID=${CF_ACCOUNT_ID}
      - CF_TUNNEL_ID=${CF_TUNNEL_ID}
      - CF_ACCESS_POLICY_ID=${CF_ACCESS_POLICY_ID}
      - CF_DOMAIN=${CF_DOMAIN}
      - DOCKER_HOST_IP=${DOCKER_HOST_IP}